set(HEADER_NAMES
   Defines.h.in
   Engine.h
   Log.h
   Pointers.h
   Shiny.h
   ShinyAssert.h
   Version.h.in
   Assets/AudioLoader.h
   Assets/DefaultImageSource.h
   Assets/MeshLoader.h
   Assets/ShaderLoader.h
   Assets/TextureLoader.h
   Audio/AudioBuffer.h
   Audio/AudioError.h
   Audio/AudioSource.h
   Audio/AudioSystem.h
   Audio/Sound.h
   Audio/Stream.h
   Graphics/Context.h
   Graphics/Framebuffer.h
   Graphics/Material.h
   Graphics/Mesh.h
   Graphics/Model.h
   Graphics/OpenGL.h
   Graphics/RenderData.h
   Graphics/Shader.h
   Graphics/ShaderProgram.h
   Graphics/Texture.h
   Graphics/TextureMaterial.h
   Graphics/Uniform.h
   Graphics/UniformTypes.h
   Graphics/Viewport.h
   Input/Controller.h
   Input/ControllerMap.h
   Input/InputDevice.h
   Input/Keyboard.h
   Input/Keys.h
   Input/Mouse.h
   Platform/IOUtils.h
   Platform/OSUtils.h
   Scene/Camera.h
   Scene/Scene.h
   Scene/SceneObject.h
   Scene/Transform.h
   Text/Font.h
   Text/FontAtlas.h
   Text/TextRenderer.h
)
