set(HEADER_NAMES
   Engine.h
   GLIncludes.h
   Log.h
   Pointers.h
   Shiny.h
   ShinyAssert.h
   Assets/DefaultImageSource.h
   Assets/MeshLoader.h
   Assets/ShaderLoader.h
   Assets/TextureLoader.h
   Graphics/Context.h
   Graphics/Framebuffer.h
   Graphics/Material.h
   Graphics/Mesh.h
   Graphics/Model.h
   Graphics/RenderData.h
   Graphics/Shader.h
   Graphics/ShaderProgram.h
   Graphics/Texture.h
   Graphics/Viewport.h
   Platform/IOUtils.h
   Platform/OSUtils.h
   Scene/Camera.h
   Scene/Scene.h
   Scene/SceneObject.h
   Scene/Transform.h
)