set(HEADER_NAMES
   Engine.h
   GLIncludes.h
   Log.h
   Pointers.h
   Shiny.h
   ShinyAssert.h
   Assets/MeshLoader.h
   Assets/ShaderLoader.h
   Graphics/Framebuffer.h
   Graphics/Mesh.h
   Graphics/Model.h
   Graphics/Shader.h
   Graphics/ShaderProgram.h
   Graphics/Texture.h
   Graphics/Viewport.h
   Platform/IOUtils.h
   Platform/OSUtils.h
)