set(SOURCE_NAMES
   Engine.cpp
   Shiny.cpp
   Assets/AudioLoader.cpp
   Assets/MeshLoader.cpp
   Assets/ShaderLoader.cpp
   Assets/TextureLoader.cpp
   Audio/AudioBuffer.cpp
   Audio/AudioSource.cpp
   Audio/AudioSystem.cpp
   Audio/Sound.cpp
   Audio/Stream.cpp
   Graphics/Context.cpp
   Graphics/Framebuffer.cpp
   Graphics/Mesh.cpp
   Graphics/Model.cpp
   Graphics/RenderData.cpp
   Graphics/Shader.cpp
   Graphics/ShaderProgram.cpp
   Graphics/Texture.cpp
   Graphics/TextureMaterial.cpp
   Input/Controller.cpp
   Input/ControllerMap.cpp
   Input/Keyboard.cpp
   Input/Mouse.cpp
   Platform/IOUtils.cpp
   Platform/OSUtils.cpp
   Scene/Camera.cpp
   Scene/Scene.cpp
   Scene/SceneObject.cpp
   Text/Font.cpp
   Text/FontAtlas.cpp
   Text/TextRenderer.cpp
)
