set(SOURCE_NAMES
   main.cpp
   Assets/MeshLoader.cpp
   Assets/ShaderLoader.cpp
   Graphics/Framebuffer.cpp
   Graphics/Mesh.cpp
   Graphics/Model.cpp
   Graphics/Shader.cpp
   Graphics/ShaderProgram.cpp
   Graphics/Texture.cpp
   Platform/IOUtils.cpp
   Platform/OSUtils.cpp
)